import { TanstackProvider } from '@examples/provider';

export const metadata = {
  title: 'Welcome to examples',
  description: 'Generated by create-nx-workspace',
};

export default function TanstackLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <TanstackProvider>{children}</TanstackProvider>;
}
