import sideMenuLink from '@examples/constants/sideMenuLink';
import {
  DocLayout,
  SharedBody,
  SharedHead,
  SharedLayout,
} from '@verizon-nextgen/shared/ui';

export const metadata = {
  title: 'Welcome to examples',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SharedLayout>
      <SharedHead />
      <SharedBody>
        <DocLayout links={sideMenuLink}>{children}</DocLayout>
      </SharedBody>
    </SharedLayout>
  );
}
